In [3]:
import pandas as pd
dataframe = pd.read_csv(r"C:\Users\Pichau\Downloads\vendas_missao_6_pandas.csv")
dataframe

,vendedor,cidade,categoria,produto,quantidade,preco,total
0,Ana,Salvador,Eletrônicos,Notebook,2,3500.0,7000.0
1,Ana,Lauro de Freitas,Acessórios,Mouse,3,50.0,150.0
2,Bruno,Salvador,Eletrônicos,Monitor,1,1200.0,1200.0
3,Bruno,Lauro de Freitas,Eletrônicos,Notebook,2,3200.0,6400.0
4,Carlos,Salvador,Acessórios,Teclado,4,50.0,200.0
5,Carlos,NaN,Eletrônicos,Notebook,1,3400.0,3400.0
6,Ana,Salvador,Eletrônicos,Monitor,2,1150.0,2300.0
7,Bruno,Salvador,Acessórios,Mouse,5,60.0,300.0
8,Carlos,Lauro de Freitas,Acessórios,Teclado,2,55.0,110.0
9,Ana,Lauro de Freitas,Eletrônicos,Notebook,1,3300.0,3300.0
10,Bruno,Salvador,NaN,Monitor,3,1100.0,3300.0
11,Carlos,Salvador,Acessórios,Mouse,4,65.0,260.0
12,Ana,Salvador,Eletrônicos,Notebook,2,3500.0,7000.0
13,Bruno,Lauro de Freitas,Acessórios,Teclado,3,NaN,NaN
14,Carlos,Salvador,Eletrônicos,Monitor,1,1200.0,1200.0
15,Bruno,Salvador,Eletrônicos,Monitor,1,1200.0,1200.0

In [6]:
missao1quant = dataframe["cidade"].value_counts()
missao1quant

cidade
Salvador            10
Lauro de Freitas     5
Name: count, dtype: int64

In [7]:
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   vendedor    16 non-null     str
 1   cidade      15 non-null     str
 2   categoria   15 non-null     str
 3   produto     16 non-null     str
 4   quantidade  16 non-null     int64
 5   preco       15 non-null     float64
 6   total       15 non-null     float64
dtypes: float64(2), int64(1), str(4)
memory usage: 1.0 KB

In [9]:
dataframe.describe()

       quantidade        preco        total
count     16.0000    15.000000    15.000000
mean       2.3125  1535.333333  2488.000000
std        1.2500  1431.772711  2525.442535
min        1.0000    50.000000   110.000000
25%        1.0000    62.500000   280.000000
50%        2.0000  1200.000000  1200.000000
75%        3.0000  3250.000000  3350.000000
max        5.0000  3500.000000  7000.000000

In [11]:
dataframe.isna().sum()

vendedor      0
cidade        1
categoria     1
produto       0
quantidade    0
preco         1
total         1
dtype: int64

In [13]:
dataframe["cidade"].fillna("S/Cidade")

0             Salvador
1     Lauro de Freitas
2             Salvador
3     Lauro de Freitas
4             Salvador
5             S/Cidade
6             Salvador
7             Salvador
8     Lauro de Freitas
9     Lauro de Freitas
10            Salvador
11            Salvador
12            Salvador
13    Lauro de Freitas
14            Salvador
15            Salvador
Name: cidade, dtype: str

In [14]:
dataframe["categoria"].fillna("S/Categoria")

0     Eletrônicos
1      Acessórios
2     Eletrônicos
3     Eletrônicos
4      Acessórios
5     Eletrônicos
6     Eletrônicos
7      Acessórios
8      Acessórios
9     Eletrônicos
10    S/Categoria
11     Acessórios
12    Eletrônicos
13     Acessórios
14    Eletrônicos
15    Eletrônicos
Name: categoria, dtype: str

In [16]:
dataframe["preco"].fillna("S/Preco")

0      3500.0
1        50.0
2      1200.0
3      3200.0
4        50.0
5      3400.0
6      1150.0
7        60.0
8        55.0
9      3300.0
10     1100.0
11       65.0
12     3500.0
13    S/Preco
14     1200.0
15     1200.0
Name: preco, dtype: object

In [17]:
dataframe["total"].fillna("S/Total")

0      7000.0
1       150.0
2      1200.0
3      6400.0
4       200.0
5      3400.0
6      2300.0
7       300.0
8       110.0
9      3300.0
10     3300.0
11      260.0
12     7000.0
13    S/Total
14     1200.0
15     1200.0
Name: total, dtype: object

In [19]:
dataframe = dataframe.fillna({
    "cidade" : "S/Cidade",
    "categoria" : "S/Categoria",
    "preco" : 0,
    "total" : 0
})
dataframe

,vendedor,cidade,categoria,produto,quantidade,preco,total
0,Ana,Salvador,Eletrônicos,Notebook,2,3500.0,7000.0
1,Ana,Lauro de Freitas,Acessórios,Mouse,3,50.0,150.0
2,Bruno,Salvador,Eletrônicos,Monitor,1,1200.0,1200.0
3,Bruno,Lauro de Freitas,Eletrônicos,Notebook,2,3200.0,6400.0
4,Carlos,Salvador,Acessórios,Teclado,4,50.0,200.0
5,Carlos,S/Cidade,Eletrônicos,Notebook,1,3400.0,3400.0
6,Ana,Salvador,Eletrônicos,Monitor,2,1150.0,2300.0
7,Bruno,Salvador,Acessórios,Mouse,5,60.0,300.0
8,Carlos,Lauro de Freitas,Acessórios,Teclado,2,55.0,110.0
9,Ana,Lauro de Freitas,Eletrônicos,Notebook,1,3300.0,3300.0
10,Bruno,Salvador,S/Categoria,Monitor,3,1100.0,3300.0
11,Carlos,Salvador,Acessórios,Mouse,4,65.0,260.0
12,Ana,Salvador,Eletrônicos,Notebook,2,3500.0,7000.0
13,Bruno,Lauro de Freitas,Acessórios,Teclado,3,0.0,0.0
14,Carlos,Salvador,Eletrônicos,Monitor,1,1200.0,1200.0
15,Bruno,Salvador,Eletrônicos,Monitor,1,1200.0,1200.0

In [23]:
dataframe.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
13    False
14    False
dtype: bool

In [21]:
dataframe = dataframe.drop_duplicated()

,vendedor,cidade,categoria,produto,quantidade,preco,total
0,Ana,Salvador,Eletrônicos,Notebook,2,3500.0,7000.0
1,Ana,Lauro de Freitas,Acessórios,Mouse,3,50.0,150.0
2,Bruno,Salvador,Eletrônicos,Monitor,1,1200.0,1200.0
3,Bruno,Lauro de Freitas,Eletrônicos,Notebook,2,3200.0,6400.0
4,Carlos,Salvador,Acessórios,Teclado,4,50.0,200.0
5,Carlos,S/Cidade,Eletrônicos,Notebook,1,3400.0,3400.0
6,Ana,Salvador,Eletrônicos,Monitor,2,1150.0,2300.0
7,Bruno,Salvador,Acessórios,Mouse,5,60.0,300.0
8,Carlos,Lauro de Freitas,Acessórios,Teclado,2,55.0,110.0
9,Ana,Lauro de Freitas,Eletrônicos,Notebook,1,3300.0,3300.0
10,Bruno,Salvador,S/Categoria,Monitor,3,1100.0,3300.0
11,Carlos,Salvador,Acessórios,Mouse,4,65.0,260.0
13,Bruno,Lauro de Freitas,Acessórios,Teclado,3,0.0,0.0
14,Carlos,Salvador,Eletrônicos,Monitor,1,1200.0,1200.0

In [26]:
vendasmaior2000 = dataframe[dataframe["total"] > 2000]
vendasmaior2000

,vendedor,cidade,categoria,produto,quantidade,preco,total
0,Ana,Salvador,Eletrônicos,Notebook,2,3500.0,7000.0
3,Bruno,Lauro de Freitas,Eletrônicos,Notebook,2,3200.0,6400.0
5,Carlos,S/Cidade,Eletrônicos,Notebook,1,3400.0,3400.0
6,Ana,Salvador,Eletrônicos,Monitor,2,1150.0,2300.0
9,Ana,Lauro de Freitas,Eletrônicos,Notebook,1,3300.0,3300.0
10,Bruno,Salvador,S/Categoria,Monitor,3,1100.0,3300.0

In [27]:
cidade_salvador = dataframe[dataframe["cidade"] == "Salvador"]
cidade_salvador

   vendedor    cidade    categoria   produto  quantidade   preco   total
0       Ana  Salvador  Eletrônicos  Notebook           2  3500.0  7000.0
2     Bruno  Salvador  Eletrônicos   Monitor           1  1200.0  1200.0
4    Carlos  Salvador   Acessórios   Teclado           4    50.0   200.0
6       Ana  Salvador  Eletrônicos   Monitor           2  1150.0  2300.0
7     Bruno  Salvador   Acessórios     Mouse           5    60.0   300.0
10    Bruno  Salvador  S/Categoria   Monitor           3  1100.0  3300.0
11   Carlos  Salvador   Acessórios     Mouse           4    65.0   260.0
14   Carlos  Salvador  Eletrônicos   Monitor           1  1200.0  1200.0

In [31]:
total_vendido_ssa = cidade_salvador["total"].sum()
total_vendido_ssa

np.float64(15760.0)

In [36]:
dataframe_vendedor = dataframe.groupby("vendedor").agg(
    faturamento_total=("total" , "sum"),
    quantidade_vendida=("quantidade" , "sum")
)

dataframe_vendedor.reset_index()

  vendedor  faturamento_total  quantidade_vendida
0      Ana            12750.0                   8
1    Bruno            11200.0                  14
2   Carlos             5170.0                  12

In [37]:
pivot_cidade_vendedor = pd.pivot_table(dataframe,index="vendedor",columns="cidade",values="total",aggfunc="sum")
pivot_cidade_vendedor

cidade    Lauro de Freitas  S/Cidade  Salvador
vendedor
Ana                 3450.0       NaN    9300.0
Bruno               6400.0       NaN    4800.0
Carlos               110.0    3400.0    1660.0

In [40]:
pivot_categoria_cidade = pd.pivot_table(dataframe,index="categoria",columns="cidade",values="total",aggfunc="sum")
pivot_categoria_cidade

cidade       Lauro de Freitas  S/Cidade  Salvador
categoria
Acessórios              260.0       NaN     760.0
Eletrônicos            9700.0    3400.0   11700.0
S/Categoria               NaN       NaN    3300.0

In [44]:
maiorvalor = pivot_categoria_cidade["Salvador"].idxmax()
datatop = pivot_categoria_cidade["Salvador"].loc[maiorvalor]
datatop

np.float64(11700.0)