In [1]:
import pandas as pd

dados = {
    "vendedor": [
        "Ana", "Bruno", "Carlos", "Ana", "Bruno",
        "Carlos", "Ana", "Bruno", "Carlos", "Ana",
        "Bruno", "Carlos", "Ana", "Bruno"
    ],

    "cidade": [
        "Salvador", "Camaçari", "salvador", "Camaçari",
        "Salvador", "Camaçari", "Salvador", "camacari",
        "Salvador", "Camaçari", "Salvador", "Camaçari",
        "Salvador", "Camaçari"
    ],

    "categoria": [
        "Eletrônicos", "Acessórios", "Eletrônicos", "Casa",
        "Acessórios", "Eletrônicos", "Casa", "Acessórios",
        "Eletrônicos", "Casa", "Acessórios", "Eletrônicos",
        "Eletrônicos", "Acessórios"
    ],

    "produto": [
        "Notebook", "Mouse", "Monitor", "Cadeira",
        "Teclado", "Notebook", "Mesa", "Mouse",
        "Monitor", "Cadeira", "Teclado", "Notebook",
        "Notebook", "Mouse"
    ],

    "preco": [
        3500, 120, "1200", 850,
        None, 3400, 700, 130,
        1150, 900, 210, 3450,
        3500, 125
    ],

    "quantidade": [
        2, 5, 2, 1,
        3, None, 2, 6,
        2, 1, 4, 2,
        2, 3
    ]
}

dataframe = pd.DataFrame(dados)
dataframe

   vendedor    cidade    categoria   produto preco  quantidade
0       Ana  Salvador  Eletrônicos  Notebook  3500         2.0
1     Bruno  Camaçari   Acessórios     Mouse   120         5.0
2    Carlos  salvador  Eletrônicos   Monitor  1200         2.0
3       Ana  Camaçari         Casa   Cadeira   850         1.0
4     Bruno  Salvador   Acessórios   Teclado  None         3.0
5    Carlos  Camaçari  Eletrônicos  Notebook  3400         NaN
6       Ana  Salvador         Casa      Mesa   700         2.0
7     Bruno  camacari   Acessórios     Mouse   130         6.0
8    Carlos  Salvador  Eletrônicos   Monitor  1150         2.0
9       Ana  Camaçari         Casa   Cadeira   900         1.0
10    Bruno  Salvador   Acessórios   Teclado   210         4.0
11   Carlos  Camaçari  Eletrônicos  Notebook  3450         2.0
12      Ana  Salvador  Eletrônicos  Notebook  3500         2.0
13    Bruno  Camaçari   Acessórios     Mouse   125         3.0

In [2]:
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   vendedor    14 non-null     str
 1   cidade      14 non-null     str
 2   categoria   14 non-null     str
 3   produto     14 non-null     str
 4   preco       13 non-null     object
 5   quantidade  13 non-null     float64
dtypes: float64(1), object(1), str(4)
memory usage: 804.0+ bytes

In [4]:
dataframe["cidade"].value_counts()

cidade
Salvador    6
Camaçari    6
salvador    1
camacari    1
Name: count, dtype: int64

In [5]:
dataframe["cidade"] = dataframe["cidade"].replace("salvador","Salvador")

In [6]:
dataframe["cidade"] = dataframe["cidade"].replace("camacari","Camaçari")

In [9]:
dataframe.isna().sum()

vendedor      0
cidade        0
categoria     0
produto       0
preco         1
quantidade    1
dtype: int64

In [10]:
dataframe["preco"] = dataframe["preco"].fillna(0)

In [11]:
dataframe["quantidade"] = dataframe["quantidade"].fillna(0.0)

In [17]:
dataframe["preco"] = pd.to_numeric(dataframe["preco"])

In [18]:
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   vendedor    14 non-null     str
 1   cidade      14 non-null     str
 2   categoria   14 non-null     str
 3   produto     14 non-null     str
 4   preco       14 non-null     int64
 5   quantidade  14 non-null     float64
dtypes: float64(1), int64(1), str(4)
memory usage: 804.0 bytes

In [19]:
dataframe["total"] = dataframe["quantidade"] * dataframe["preco"]
dataframe

   vendedor    cidade    categoria   produto  preco  quantidade   total
0       Ana  Salvador  Eletrônicos  Notebook   3500         2.0  7000.0
1     Bruno  Camaçari   Acessórios     Mouse    120         5.0   600.0
2    Carlos  Salvador  Eletrônicos   Monitor   1200         2.0  2400.0
3       Ana  Camaçari         Casa   Cadeira    850         1.0   850.0
4     Bruno  Salvador   Acessórios   Teclado      0         3.0     0.0
5    Carlos  Camaçari  Eletrônicos  Notebook   3400         0.0     0.0
6       Ana  Salvador         Casa      Mesa    700         2.0  1400.0
7     Bruno  Camaçari   Acessórios     Mouse    130         6.0   780.0
8    Carlos  Salvador  Eletrônicos   Monitor   1150         2.0  2300.0
9       Ana  Camaçari         Casa   Cadeira    900         1.0   900.0
10    Bruno  Salvador   Acessórios   Teclado    210         4.0   840.0
11   Carlos  Camaçari  Eletrônicos  Notebook   3450         2.0  6900.0
12      Ana  Salvador  Eletrônicos  Notebook   3500         2.0  7000.0
13    Bruno  Camaçari   Acessórios     Mouse    125         3.0   375.0

In [20]:
dataframecidade = dataframe.groupby("cidade").agg(
    faturamento_total = ("total","sum"),
    quantidade_total = ("quantidade","sum")
).reset_index().sort_values(by="faturamento_total",ascending=False)
dataframecidade

     cidade  faturamento_total  quantidade_total
1  Salvador            20940.0              17.0
0  Camaçari            10405.0              18.0

In [25]:
dataframecidprod = pd.pivot_table(dataframe,index="produto",columns="cidade",values="total",aggfunc="sum").fillna(0.0)
dataframecidprod

cidade    Camaçari  Salvador
produto
Cadeira     1750.0       0.0
Mesa           0.0    1400.0
Monitor        0.0    4700.0
Mouse       1755.0       0.0
Notebook    6900.0   14000.0
Teclado        0.0     840.0