In [1]:
import pandas as pd

In [5]:

dados = {
    "rodada": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    
    "adversario": [
        "Flamengo", "Palmeiras", "Gremio", "Sport",
        "Cruzeiro", "Fluminense", "Botafogo", "Santos",
        "Vasco", "Corinthians", "Internacional", "Fortaleza"
    ],
    
    "mando": [
        "Casa", "Fora", "Casa", "Fora",
        "Casa", "Fora", "Casa", "Casa",
        "Fora", "Casa", "Fora", "Casa"
    ],
    
    "gols_bahia": [2, 1, 3, 0, 2, 1, 2, 4, 1, 2, 0, 3],
    
    "gols_adversario": [1, 2, 0, 1, 1, 1, 2, 2, 1, 0, 2, 1],
    
    "finalizacoes": [12, 8, 15, 7, 13, 10, 11, 18, 9, 14, 6, 16],
    
    "escanteios": [6, 3, 8, 2, 5, 4, 7, 9, 3, 6, 2, 8],
    
    "cartoes": [2, 4, 1, 3, 2, 2, 5, 1, 3, 2, 4, 1]
}

df = pd.DataFrame(dados)

df.to_csv("bahia_brasileirao.csv", index=False)

df

,rodada,adversario,mando,gols_bahia,gols_adversario,finalizacoes,escanteios,cartoes
0,1,Flamengo,Casa,2,1,12,6,2
1,2,Palmeiras,Fora,1,2,8,3,4
2,3,Gremio,Casa,3,0,15,8,1
3,4,Sport,Fora,0,1,7,2,3
4,5,Cruzeiro,Casa,2,1,13,5,2
5,6,Fluminense,Fora,1,1,10,4,2
6,7,Botafogo,Casa,2,2,11,7,5
7,8,Santos,Casa,4,2,18,9,1
8,9,Vasco,Fora,1,1,9,3,3
9,10,Corinthians,Casa,2,0,14,6,2
10,11,Internacional,Fora,0,2,6,2,4
11,12,Fortaleza,Casa,3,1,16,8,1

In [12]:
df["rodada"].count()

np.int64(12)

In [16]:
df["finalizacoes"].mean()

np.float64(11.583333333333334)

In [17]:
df["escanteios"].max()

np.int64(9)

In [31]:
for indice, linha in df.iterrows():
    if linha["gols_bahia"] > linha["gols_adversario"]:
        df.loc[indice, "resultado"] = "Triunfo"
    elif linha["gols_bahia"] == linha["gols_adversario"]:
        df.loc[indice, "resultado"] = "Empate"
    else:
        df.loc[indice, "resultado"] = "Derrota"

df

,rodada,adversario,mando,gols_bahia,gols_adversario,finalizacoes,escanteios,cartoes,resultado
0,1,Flamengo,Casa,2,1,12,6,2,Triunfo
1,2,Palmeiras,Fora,1,2,8,3,4,Derrota
2,3,Gremio,Casa,3,0,15,8,1,Triunfo
3,4,Sport,Fora,0,1,7,2,3,Derrota
4,5,Cruzeiro,Casa,2,1,13,5,2,Triunfo
5,6,Fluminense,Fora,1,1,10,4,2,Empate
6,7,Botafogo,Casa,2,2,11,7,5,Empate
7,8,Santos,Casa,4,2,18,9,1,Triunfo
8,9,Vasco,Fora,1,1,9,3,3,Empate
9,10,Corinthians,Casa,2,0,14,6,2,Triunfo
10,11,Internacional,Fora,0,2,6,2,4,Derrota
11,12,Fortaleza,Casa,3,1,16,8,1,Triunfo

In [32]:
df["resultado"].value_counts()

resultado
Triunfo    6
Derrota    3
Empate     3
Name: count, dtype: int64

In [55]:
pontosdispcasa = df["mando"].value_counts()["Casa"] * 3
pontosdispfora = df["mando"].value_counts()["Fora"] * 3

pontoscasa = 0
pontosfora = 0

for indice, linha in df.iterrows():

    if linha["mando"] == "Casa":
        if linha["resultado"] == "Triunfo":
            pontoscasa += 3
        elif linha["resultado"] == "Empate":
            pontoscasa += 1

    if linha["mando"] == "Fora":
        if linha["resultado"] == "Triunfo":
            pontosfora += 3
        elif linha["resultado"] == "Empate":
            pontosfora += 1

aproveitamentocasa = pontoscasa / pontosdispcasa * 100
aproveitamentofora = pontosfora / pontosdispfora * 100

np.float64(13.333333333333334)

In [57]:
maisgolssofridos = df["gols_bahia"].idxmax()
partida = df.loc[maisgolssofridos]
partida

rodada                   8
adversario          Santos
mando                 Casa
gols_bahia               4
gols_adversario          2
finalizacoes            18
escanteios               9
cartoes                  1
resultado          Triunfo
Name: 7, dtype: object

In [59]:
golsfora = 0
golscasa = 0
for indice,linha in df.iterrows():
    if linha["mando"] == "Casa":
        golscasa += linha["gols_bahia"]
    else:
        golsfora += linha["gols_bahia"]


if golscasa > golsfora:
    print(f"O Bahia fez mais gols em casa -> Casa {golscasa} x {golsfora} Fora")
elif golscasa == golsfora:
    print(f"O Bahia empatou em gols em Casa e Fora -> Casa {golscasa} x {golsfora} Fora")
else:
    print(f"O Bahia fez mais gols fora de casa -> Casa {golscasa} x {golsfora} Fora")

O Bahia fez mais gols em casa -> Casa 18 x 3 Fora

In [63]:
triunfofora = 0
triunfocasa = 0
for indice,linha in df.iterrows():
    if linha["mando"] == "Casa":
        if linha["resultado"] == "Triunfo":
            triunfocasa += 1

    if linha["mando"] == "Fora":
        if linha["resultado"] == "Triunfo":
            triunfofora += 1


if triunfocasa > triunfofora:
    print(f"O Bahia triunfou mais em casa -> Casa {triunfocasa} x {triunfofora} Fora")
elif triunfocasa == triunfofora:
    print(f"O Bahia empatou em triunfos em Casa e Fora -> Casa {triunfocasa} x {triunfofora} Fora")
else:
    print(f"O Bahia triunfou mais gols fora de casa -> Casa {triunfocasa} x {triunfofora} Fora")

O Bahia triunfou mais em casa -> Casa 6 x 0 Fora