In [1]:
import pandas as pd
dados = {
    "jogador": [
        "Everton Ribeiro", "Erick Pulga", "Jean Lucas",
        "Luciano Juba", "Everton Ribeiro", "Erick Pulga",
        "Jean Lucas", "Luciano Juba"
    ],
    "posicao": [
        "Meia", "Atacante", "Meia", "Lateral",
        "Meia", "Atacante", "Meia", "Lateral"
    ],
    "finalizacoes": [2, 5, 3, 1, 4, 6, 2, 3],
    "passes_certos": [45, 18, 52, 38, 41, 20, 48, 35],
    "nota": [7.2, 8.5, 7.8, 7.0, 7.6, 9.0, 7.4, 7.3]
}
dataframe = pd.DataFrame(dados)
dataframe

           jogador   posicao  finalizacoes  passes_certos  nota
0  Everton Ribeiro      Meia             2             45   7.2
1      Erick Pulga  Atacante             5             18   8.5
2       Jean Lucas      Meia             3             52   7.8
3     Luciano Juba   Lateral             1             38   7.0
4  Everton Ribeiro      Meia             4             41   7.6
5      Erick Pulga  Atacante             6             20   9.0
6       Jean Lucas      Meia             2             48   7.4
7     Luciano Juba   Lateral             3             35   7.3

In [24]:
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   jogador        8 non-null      str
 1   posicao        8 non-null      str
 2   finalizacoes   8 non-null      int64
 3   passes_certos  8 non-null      int64
 4   nota           8 non-null      float64
dtypes: float64(1), int64(2), str(2)
memory usage: 452.0 bytes

In [12]:
quantdados = dataframe["nota"].count()
print(f"Existem {quantdados} registros no dataframe.")

Existem 8 registros no dataframe.

In [18]:
topnota = dataframe["nota"].idxmax()
infotop = dataframe.loc[topnota]
infotop
print(f"O melhor desempenho foi da seguinte ficha:\n{infotop}")

O melhor desempenho foi da seguinte ficha:
jogador          Erick Pulga
posicao             Atacante
finalizacoes               6
passes_certos             20
nota                     9.0
Name: 5, dtype: object

In [20]:
datafilter = dataframe[dataframe["nota"] >= 8]
datafilter

       jogador   posicao  finalizacoes  passes_certos  nota
1  Erick Pulga  Atacante             5             18   8.5
5  Erick Pulga  Atacante             6             20   9.0

In [27]:
contadorfinalizacoesmaior3 = 0
for linha,coluna in dataframe.iterrows():
    if coluna["finalizacoes"] > 3:
        contadorfinalizacoesmaior3 += 1
    else:
        contadorfinalizacoesmaior3 += 0

print(f"{contadorfinalizacoesmaior3} registros tiveram mais que três finalizações!")

3 registros tiveram mais que três finalizações!

In [37]:
contador = 0

for indice,linha in dataframe.iterrows():
    if linha["finalizacoes"] >= 5:
        contador += 1
        print(f"{linha['jogador']} com {linha['finalizacoes']} finalizações")

print(f"{contador} registros tiveram cinco ou mais finalizações!")

Erick Pulga com 5 finalizações
Erick Pulga com 6 finalizações
2 registros tiveram cinco ou mais finalizações!