In [2]:
import pandas as pd

dados = {
    "vendedor": [
        "Ana", "Bruno", "Carlos", "Ana",
        "Bruno", "Carlos", "Ana", "Bruno",
        "Carlos", "Ana", "Bruno", "Carlos"
    ],

    "cidade": [
        "Salvador", "Lauro de Freitas", "Salvador", "Salvador",
        "Lauro de Freitas", "Lauro de Freitas", "Salvador", "Salvador",
        "Lauro de Freitas", "Lauro de Freitas", "salvador", "Salvador"
    ],

    "categoria": [
        "Eletrônicos", "Acessórios", "Eletrônicos", "Eletrônicos",
        "Eletrônicos", "Acessórios", "Eletrônicos", "Acessórios",
        "Acessórios", "Eletrônicos", "Eletrônicos", "Eletrônicos"
    ],

    "produto": [
        "Notebook", "Mouse", "Monitor", "Notebook",
        "Teclado", "Mouse", "Monitor", "Teclado",
        "Mouse", "Notebook", "Notebook", "Monitor"
    ],

    "preco": [
        3500, 150, 1200, 3500,
        None, 180, "1100", 200,
        180, 3200, 3200, 1200
    ],

    "quantidade": [
        2, 5, 2, 2,
        1, None, 1, 3,
        4, 1, 1, 2
    ]
}

dataframe = pd.DataFrame(dados)
dataframe

   vendedor            cidade    categoria   produto preco  quantidade
0       Ana          Salvador  Eletrônicos  Notebook  3500         2.0
1     Bruno  Lauro de Freitas   Acessórios     Mouse   150         5.0
2    Carlos          Salvador  Eletrônicos   Monitor  1200         2.0
3       Ana          Salvador  Eletrônicos  Notebook  3500         2.0
4     Bruno  Lauro de Freitas  Eletrônicos   Teclado  None         1.0
5    Carlos  Lauro de Freitas   Acessórios     Mouse   180         NaN
6       Ana          Salvador  Eletrônicos   Monitor  1100         1.0
7     Bruno          Salvador   Acessórios   Teclado   200         3.0
8    Carlos  Lauro de Freitas   Acessórios     Mouse   180         4.0
9       Ana  Lauro de Freitas  Eletrônicos  Notebook  3200         1.0
10    Bruno          salvador  Eletrônicos  Notebook  3200         1.0
11   Carlos          Salvador  Eletrônicos   Monitor  1200         2.0

In [4]:
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   vendedor    12 non-null     str
 1   cidade      12 non-null     str
 2   categoria   12 non-null     str
 3   produto     12 non-null     str
 4   preco       11 non-null     object
 5   quantidade  11 non-null     float64
dtypes: float64(1), object(1), str(4)
memory usage: 708.0+ bytes

In [5]:
dataframe.describe()

       quantidade
count   11.000000
mean     2.181818
std      1.328020
min      1.000000
25%      1.000000
50%      2.000000
75%      2.500000
max      5.000000

In [7]:
dataframe.isnull()

    vendedor  cidade  categoria  produto  preco  quantidade
0      False   False      False    False  False       False
1      False   False      False    False  False       False
2      False   False      False    False  False       False
3      False   False      False    False  False       False
4      False   False      False    False   True       False
5      False   False      False    False  False        True
6      False   False      False    False  False       False
7      False   False      False    False  False       False
8      False   False      False    False  False       False
9      False   False      False    False  False       False
10     False   False      False    False  False       False
11     False   False      False    False  False       False

In [8]:
dataframe.isnull().sum()

vendedor      0
cidade        0
categoria     0
produto       0
preco         1
quantidade    1
dtype: int64

In [10]:
dataframe.duplicated()

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
dtype: bool

In [11]:
dataframe.duplicated().sum()

np.int64(2)

In [13]:
dataframe["categoria"].describe()

count              12
unique              2
top       Eletrônicos
freq                8
Name: categoria, dtype: object

In [15]:
dataframe["produto"].describe()

count           12
unique           4
top       Notebook
freq             4
Name: produto, dtype: object

In [16]:
dataframe

   vendedor            cidade    categoria   produto preco  quantidade
0       Ana          Salvador  Eletrônicos  Notebook  3500         2.0
1     Bruno  Lauro de Freitas   Acessórios     Mouse   150         5.0
2    Carlos          Salvador  Eletrônicos   Monitor  1200         2.0
3       Ana          Salvador  Eletrônicos  Notebook  3500         2.0
4     Bruno  Lauro de Freitas  Eletrônicos   Teclado  None         1.0
5    Carlos  Lauro de Freitas   Acessórios     Mouse   180         NaN
6       Ana          Salvador  Eletrônicos   Monitor  1100         1.0
7     Bruno          Salvador   Acessórios   Teclado   200         3.0
8    Carlos  Lauro de Freitas   Acessórios     Mouse   180         4.0
9       Ana  Lauro de Freitas  Eletrônicos  Notebook  3200         1.0
10    Bruno          salvador  Eletrônicos  Notebook  3200         1.0
11   Carlos          Salvador  Eletrônicos   Monitor  1200         2.0

In [29]:
dataframe = pd.DataFrame(dados)

In [30]:
dataframe["preco"] = dataframe["preco"].fillna(0)

In [31]:
dataframe["quantidade"] = dataframe["quantidade"].fillna(0)

In [27]:
dataframe = dataframe.drop_duplicates()

In [32]:
dataframe["cidade"].value_counts()

cidade
Salvador            6
Lauro de Freitas    5
salvador            1
Name: count, dtype: int64

In [34]:
dataframe["cidade"] = dataframe["cidade"].replace("salvador" , "Salvador")

In [37]:
dataframe["preco"] = pd.to_numeric(dataframe["preco"])

In [38]:
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   vendedor    12 non-null     str
 1   cidade      12 non-null     str
 2   categoria   12 non-null     str
 3   produto     12 non-null     str
 4   preco       12 non-null     int64
 5   quantidade  12 non-null     float64
dtypes: float64(1), int64(1), str(4)
memory usage: 708.0 bytes

In [39]:
dataframe

   vendedor            cidade    categoria   produto  preco  quantidade
0       Ana          Salvador  Eletrônicos  Notebook   3500         2.0
1     Bruno  Lauro de Freitas   Acessórios     Mouse    150         5.0
2    Carlos          Salvador  Eletrônicos   Monitor   1200         2.0
3       Ana          Salvador  Eletrônicos  Notebook   3500         2.0
4     Bruno  Lauro de Freitas  Eletrônicos   Teclado      0         1.0
5    Carlos  Lauro de Freitas   Acessórios     Mouse    180         0.0
6       Ana          Salvador  Eletrônicos   Monitor   1100         1.0
7     Bruno          Salvador   Acessórios   Teclado    200         3.0
8    Carlos  Lauro de Freitas   Acessórios     Mouse    180         4.0
9       Ana  Lauro de Freitas  Eletrônicos  Notebook   3200         1.0
10    Bruno          Salvador  Eletrônicos  Notebook   3200         1.0
11   Carlos          Salvador  Eletrônicos   Monitor   1200         2.0

In [40]:
dataframe["total"] = dataframe["quantidade"] * dataframe["preco"]

In [44]:
relat_vend = dataframe.groupby("vendedor").agg(
    faturamento_total=("total","sum"),
    quantidade_total=("quantidade","sum")
).reset_index().sort_values(by="faturamento_total",ascending=False)
relat_vend

  vendedor  faturamento_total  quantidade_total
0      Ana            18300.0               6.0
2   Carlos             5520.0               8.0
1    Bruno             4550.0              10.0

In [45]:
relat_cid = dataframe.groupby("cidade").agg(
    faturamento_total=("total","sum"),
    quantidade_total=("quantidade","sum")
).reset_index().sort_values(by="faturamento_total",ascending=False)
relat_cid

             cidade  faturamento_total  quantidade_total
1          Salvador            23700.0              13.0
0  Lauro de Freitas             4670.0              11.0

In [49]:
dataframeprod = dataframe.groupby("produto").agg(
    faturamento_total=("total","sum")
).reset_index()
dataframeprod

    produto  faturamento_total
0   Monitor             5900.0
1     Mouse             1470.0
2  Notebook            20400.0
3   Teclado              600.0

In [ ]:
topprod = dataframeprod["faturamento_total"].idxmax()
dataframetopprod = dataframeprod.loc[topprod]
dataframetopprod