In [1]:
import pandas as pd

dados = {
    "vendedor": [
        "Ana", "Bruno", "Carlos", "Ana", "Bruno",
        "Carlos", "Ana", "Bruno", "Carlos", "Ana",
        "Bruno", "Carlos", "Ana"
    ],

    "cidade": [
        "Salvador", "Camaçari", "salvador", "Camaçari", "Salvador",
        "Camaçari", "Salvador", "camacari", "Salvador", "Camaçari",
        "Salvador", "Camaçari", "Salvador"
    ],

    "categoria": [
        "Eletrônicos", "Acessórios", "Eletrônicos", "Casa",
        "Acessórios", "Eletrônicos", "Casa", "Acessórios",
        "Eletrônicos", "Casa", "Acessórios", "Eletrônicos",
        "Eletrônicos"
    ],

    "produto": [
        "Notebook", "Mouse", "Monitor", "Cadeira",
        "Teclado", "Notebook", "Mesa", "Mouse",
        "Monitor", "Cadeira", "Teclado", "Notebook",
        "Notebook"
    ],

    "preco": [
        3500, 120, "1200", 850,
        None, 3400, 700, 130,
        1150, 900, 210, 3450,
        3500
    ],

    "quantidade": [
        2, 5, 2, 1,
        3, None, 2, 6,
        2, 1, 4, 2,
        2
    ]
}

dataframe = pd.DataFrame(dados)
dataframe

   vendedor    cidade    categoria   produto preco  quantidade
0       Ana  Salvador  Eletrônicos  Notebook  3500         2.0
1     Bruno  Camaçari   Acessórios     Mouse   120         5.0
2    Carlos  salvador  Eletrônicos   Monitor  1200         2.0
3       Ana  Camaçari         Casa   Cadeira   850         1.0
4     Bruno  Salvador   Acessórios   Teclado  None         3.0
5    Carlos  Camaçari  Eletrônicos  Notebook  3400         NaN
6       Ana  Salvador         Casa      Mesa   700         2.0
7     Bruno  camacari   Acessórios     Mouse   130         6.0
8    Carlos  Salvador  Eletrônicos   Monitor  1150         2.0
9       Ana  Camaçari         Casa   Cadeira   900         1.0
10    Bruno  Salvador   Acessórios   Teclado   210         4.0
11   Carlos  Camaçari  Eletrônicos  Notebook  3450         2.0
12      Ana  Salvador  Eletrônicos  Notebook  3500         2.0

In [3]:
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   vendedor    13 non-null     str
 1   cidade      13 non-null     str
 2   categoria   13 non-null     str
 3   produto     13 non-null     str
 4   preco       12 non-null     object
 5   quantidade  12 non-null     float64
dtypes: float64(1), object(1), str(4)
memory usage: 756.0+ bytes

In [5]:
dataframe.drop_duplicates()

   vendedor    cidade    categoria   produto preco  quantidade
0       Ana  Salvador  Eletrônicos  Notebook  3500         2.0
1     Bruno  Camaçari   Acessórios     Mouse   120         5.0
2    Carlos  salvador  Eletrônicos   Monitor  1200         2.0
3       Ana  Camaçari         Casa   Cadeira   850         1.0
4     Bruno  Salvador   Acessórios   Teclado  None         3.0
5    Carlos  Camaçari  Eletrônicos  Notebook  3400         NaN
6       Ana  Salvador         Casa      Mesa   700         2.0
7     Bruno  camacari   Acessórios     Mouse   130         6.0
8    Carlos  Salvador  Eletrônicos   Monitor  1150         2.0
9       Ana  Camaçari         Casa   Cadeira   900         1.0
10    Bruno  Salvador   Acessórios   Teclado   210         4.0
11   Carlos  Camaçari  Eletrônicos  Notebook  3450         2.0

In [10]:
dataframe["cidade"].value_counts()

cidade
Salvador    6
Camaçari    5
salvador    1
camacari    1
Name: count, dtype: int64

In [11]:
dataframe.replace("camacari","Camaçari")

   vendedor    cidade    categoria   produto preco  quantidade
0       Ana  Salvador  Eletrônicos  Notebook  3500         2.0
1     Bruno  Camaçari   Acessórios     Mouse   120         5.0
2    Carlos  salvador  Eletrônicos   Monitor  1200         2.0
3       Ana  Camaçari         Casa   Cadeira   850         1.0
4     Bruno  Salvador   Acessórios   Teclado  None         3.0
5    Carlos  Camaçari  Eletrônicos  Notebook  3400         NaN
6       Ana  Salvador         Casa      Mesa   700         2.0
7     Bruno  Camaçari   Acessórios     Mouse   130         6.0
8    Carlos  Salvador  Eletrônicos   Monitor  1150         2.0
9       Ana  Camaçari         Casa   Cadeira   900         1.0
10    Bruno  Salvador   Acessórios   Teclado   210         4.0
11   Carlos  Camaçari  Eletrônicos  Notebook  3450         2.0
12      Ana  Salvador  Eletrônicos  Notebook  3500         2.0

In [12]:
dataframe.replace("salvador","Salvador")

   vendedor    cidade    categoria   produto preco  quantidade
0       Ana  Salvador  Eletrônicos  Notebook  3500         2.0
1     Bruno  Camaçari   Acessórios     Mouse   120         5.0
2    Carlos  Salvador  Eletrônicos   Monitor  1200         2.0
3       Ana  Camaçari         Casa   Cadeira   850         1.0
4     Bruno  Salvador   Acessórios   Teclado  None         3.0
5    Carlos  Camaçari  Eletrônicos  Notebook  3400         NaN
6       Ana  Salvador         Casa      Mesa   700         2.0
7     Bruno  camacari   Acessórios     Mouse   130         6.0
8    Carlos  Salvador  Eletrônicos   Monitor  1150         2.0
9       Ana  Camaçari         Casa   Cadeira   900         1.0
10    Bruno  Salvador   Acessórios   Teclado   210         4.0
11   Carlos  Camaçari  Eletrônicos  Notebook  3450         2.0
12      Ana  Salvador  Eletrônicos  Notebook  3500         2.0

In [17]:
dataframe["preco"] = dataframe["preco"].fillna(0)

In [18]:
dataframe["quantidade"] = dataframe["quantidade"].fillna(0.0)

In [33]:
dataframe["preco"] = pd.to_numeric(dataframe["preco"]).astype(float)
dataframe["total"] = dataframe["quantidade"] * dataframe["preco"]
dataframe

   vendedor    cidade    categoria   produto   preco  quantidade   total
0       Ana  Salvador  Eletrônicos  Notebook  3500.0         2.0  7000.0
1     Bruno  Camaçari   Acessórios     Mouse   120.0         5.0   600.0
2    Carlos  salvador  Eletrônicos   Monitor  1200.0         2.0  2400.0
3       Ana  Camaçari         Casa   Cadeira   850.0         1.0   850.0
4     Bruno  Salvador   Acessórios   Teclado     0.0         3.0     0.0
5    Carlos  Camaçari  Eletrônicos  Notebook  3400.0         0.0     0.0
6       Ana  Salvador         Casa      Mesa   700.0         2.0  1400.0
7     Bruno  camacari   Acessórios     Mouse   130.0         6.0   780.0
8    Carlos  Salvador  Eletrônicos   Monitor  1150.0         2.0  2300.0
9       Ana  Camaçari         Casa   Cadeira   900.0         1.0   900.0
10    Bruno  Salvador   Acessórios   Teclado   210.0         4.0   840.0
11   Carlos  Camaçari  Eletrônicos  Notebook  3450.0         2.0  6900.0
12      Ana  Salvador  Eletrônicos  Notebook  3500.0         2.0  7000.0

In [34]:
dataframecategoria = dataframe.groupby("categoria").agg(
    faturamento_total=("total","sum"),
    quantidade_total=("quantidade","sum")
).reset_index().sort_values(by="faturamento_total",ascending=False)
dataframecategoria

     categoria  faturamento_total  quantidade_total
2  Eletrônicos            25600.0              10.0
1         Casa             3150.0               4.0
0   Acessórios             2220.0              18.0