In [1]:
import pandas as pd

dados = {
    "jogador": [
        "Everton Ribeiro",
        "Erick Pulga",
        "Jean Lucas",
        "Luciano Juba",
        "Willian José",
        "Nestor",
        "Ademir",
        "Erick",
        "Alejo Veliz",
        "Kike Olivera",
        "Everton Ribeiro",
        "Erick Pulga"
    ],

    "competicao": [
        "Brasileirao",
        "Brasileirao",
        "Brasileirao",
        "Brasileirao",
        "Brasileirao",
        "Copa do Brasil",
        "Copa do Brasil",
        "Copa do Brasil",
        "Copa do Nordeste",
        "Copa do Nordeste",
        "Copa do Nordeste",
        "Copa do Nordeste"
    ],

    "gols": [
        3, 8, 4, 3, 5, 2,
        4, 3, 3, 2, 2, 5
    ],

    "assistencias": [
        5, 4, 3, 6, 2, 4,
        3, 2, 2, 4, 5, 3
    ]
}

dataframe = pd.DataFrame(dados)
dataframe

            jogador        competicao  gols  assistencias
0   Everton Ribeiro       Brasileirao     3             5
1       Erick Pulga       Brasileirao     8             4
2        Jean Lucas       Brasileirao     4             3
3      Luciano Juba       Brasileirao     3             6
4      Willian José       Brasileirao     5             2
5            Nestor    Copa do Brasil     2             4
6            Ademir    Copa do Brasil     4             3
7             Erick    Copa do Brasil     3             2
8       Alejo Veliz  Copa do Nordeste     3             2
9      Kike Olivera  Copa do Nordeste     2             4
10  Everton Ribeiro  Copa do Nordeste     2             5
11      Erick Pulga  Copa do Nordeste     5             3

In [11]:
dataframe = dataframe.drop_duplicates()
dataframe

            jogador        competicao  gols  assistencias
0   Everton Ribeiro       Brasileirao     3             5
1       Erick Pulga       Brasileirao     8             4
2        Jean Lucas       Brasileirao     4             3
3      Luciano Juba       Brasileirao     3             6
4      Willian José       Brasileirao     5             2
5            Nestor    Copa do Brasil     2             4
6            Ademir    Copa do Brasil     4             3
7             Erick    Copa do Brasil     3             2
8       Alejo Veliz  Copa do Nordeste     3             2
9      Kike Olivera  Copa do Nordeste     2             4
10  Everton Ribeiro  Copa do Nordeste     2             5
11      Erick Pulga  Copa do Nordeste     5             3

In [12]:
dataframe["participacoes"] = dataframe["gols"] + dataframe["assistencias"]
dataframe

            jogador        competicao  gols  assistencias  participacoes
0   Everton Ribeiro       Brasileirao     3             5              8
1       Erick Pulga       Brasileirao     8             4             12
2        Jean Lucas       Brasileirao     4             3              7
3      Luciano Juba       Brasileirao     3             6              9
4      Willian José       Brasileirao     5             2              7
5            Nestor    Copa do Brasil     2             4              6
6            Ademir    Copa do Brasil     4             3              7
7             Erick    Copa do Brasil     3             2              5
8       Alejo Veliz  Copa do Nordeste     3             2              5
9      Kike Olivera  Copa do Nordeste     2             4              6
10  Everton Ribeiro  Copa do Nordeste     2             5              7
11      Erick Pulga  Copa do Nordeste     5             3              8

In [16]:
dataframepart = dataframe.groupby(["jogador","competicao"]).agg(
    participacoes_total = ("participacoes","sum")
).reset_index().sort_values(by="participacoes_total",ascending=False)

dataframepart

            jogador        competicao  participacoes_total
3       Erick Pulga       Brasileirao                   12
9      Luciano Juba       Brasileirao                    9
4       Erick Pulga  Copa do Nordeste                    8
5   Everton Ribeiro       Brasileirao                    8
7        Jean Lucas       Brasileirao                    7
11     Willian José       Brasileirao                    7
0            Ademir    Copa do Brasil                    7
6   Everton Ribeiro  Copa do Nordeste                    7
8      Kike Olivera  Copa do Nordeste                    6
10           Nestor    Copa do Brasil                    6
2             Erick    Copa do Brasil                    5
1       Alejo Veliz  Copa do Nordeste                    5

In [21]:
with pd.ExcelWriter("Dados de desempenho do Bahia.xlsx") as writer:
    dataframe.to_excel(writer,index=False,sheet_name="Dados_Tratados_SemDuplicidade")
    dataframepart.to_excel(writer,index=False,sheet_name="Dados_Desempenho_Por_Competição")