In [11]:
import pandas as pd

dados = {
    "vendedor": ["Ana", "Bruno", "Carlos", "Ana", "Bruno", "Carlos",
                 "Ana", "Bruno", "Carlos", "Ana", "Bruno", "Carlos", "Ana"],
    
    "cidade": ["Salvador", "Camaçari", "salvador", "Camaçari", "Salvador",
               "Camaçari", "salvador", "Camaçari", "Salvador", "Camaçari",
               "Salvador", "Camaçari", "Salvador"],
    
    "categoria": ["Eletrônicos", "Acessórios", "Eletrônicos", "Acessórios",
                  "Eletrônicos", "Acessórios", "Eletrônicos", "Eletrônicos",
                  "Acessórios", "Eletrônicos", "Acessórios", "Eletrônicos",
                  "Eletrônicos"],
    
    "produto": ["Notebook", "Mouse", "Monitor", "Teclado", "Notebook",
                "Mouse", "Monitor", "Notebook", "Teclado", "Monitor",
                "Mouse", "Notebook", "Notebook"],
    
    "preco": [3500, 120, 1200, 200, None, 150, 1150, 3300,
              220, 1250, 130, 3450, 3500],
    
    "quantidade": [2, 5, 2, 3, 1, None, 2, 1, 3, 1, 6, 2, 2]
}

df = pd.DataFrame(dados)

df.to_csv("dados_baguncados_2.csv", index=False)

df

   vendedor    cidade    categoria   produto   preco  quantidade
0       Ana  Salvador  Eletrônicos  Notebook  3500.0         2.0
1     Bruno  Camaçari   Acessórios     Mouse   120.0         5.0
2    Carlos  salvador  Eletrônicos   Monitor  1200.0         2.0
3       Ana  Camaçari   Acessórios   Teclado   200.0         3.0
4     Bruno  Salvador  Eletrônicos  Notebook     NaN         1.0
5    Carlos  Camaçari   Acessórios     Mouse   150.0         NaN
6       Ana  salvador  Eletrônicos   Monitor  1150.0         2.0
7     Bruno  Camaçari  Eletrônicos  Notebook  3300.0         1.0
8    Carlos  Salvador   Acessórios   Teclado   220.0         3.0
9       Ana  Camaçari  Eletrônicos   Monitor  1250.0         1.0
10    Bruno  Salvador   Acessórios     Mouse   130.0         6.0
11   Carlos  Camaçari  Eletrônicos  Notebook  3450.0         2.0
12      Ana  Salvador  Eletrônicos  Notebook  3500.0         2.0

In [15]:
df["quantidade"] = df["quantidade"].fillna(0.0)
df

   vendedor    cidade    categoria   produto   preco  quantidade
0       Ana  Salvador  Eletrônicos  Notebook  3500.0         2.0
1     Bruno  Camaçari   Acessórios     Mouse   120.0         5.0
2    Carlos  salvador  Eletrônicos   Monitor  1200.0         2.0
3       Ana  Camaçari   Acessórios   Teclado   200.0         3.0
4     Bruno  Salvador  Eletrônicos  Notebook     0.0         1.0
5    Carlos  Camaçari   Acessórios     Mouse   150.0         0.0
6       Ana  salvador  Eletrônicos   Monitor  1150.0         2.0
7     Bruno  Camaçari  Eletrônicos  Notebook  3300.0         1.0
8    Carlos  Salvador   Acessórios   Teclado   220.0         3.0
9       Ana  Camaçari  Eletrônicos   Monitor  1250.0         1.0
10    Bruno  Salvador   Acessórios     Mouse   130.0         6.0
11   Carlos  Camaçari  Eletrônicos  Notebook  3450.0         2.0
12      Ana  Salvador  Eletrônicos  Notebook  3500.0         2.0

In [13]:
df["preco"] = df["preco"].fillna(0.00)
df

   vendedor    cidade    categoria   produto   preco  quantidade
0       Ana  Salvador  Eletrônicos  Notebook  3500.0         2.0
1     Bruno  Camaçari   Acessórios     Mouse   120.0         5.0
2    Carlos  salvador  Eletrônicos   Monitor  1200.0         2.0
3       Ana  Camaçari   Acessórios   Teclado   200.0         3.0
4     Bruno  Salvador  Eletrônicos  Notebook     0.0         1.0
5    Carlos  Camaçari   Acessórios     Mouse   150.0         0.0
6       Ana  salvador  Eletrônicos   Monitor  1150.0         2.0
7     Bruno  Camaçari  Eletrônicos  Notebook  3300.0         1.0
8    Carlos  Salvador   Acessórios   Teclado   220.0         3.0
9       Ana  Camaçari  Eletrônicos   Monitor  1250.0         1.0
10    Bruno  Salvador   Acessórios     Mouse   130.0         6.0
11   Carlos  Camaçari  Eletrônicos  Notebook  3450.0         2.0
12      Ana  Salvador  Eletrônicos  Notebook  3500.0         2.0

In [18]:
df = df.drop_duplicates()
df

   vendedor    cidade    categoria   produto   preco  quantidade
0       Ana  Salvador  Eletrônicos  Notebook  3500.0         2.0
1     Bruno  Camaçari   Acessórios     Mouse   120.0         5.0
2    Carlos  salvador  Eletrônicos   Monitor  1200.0         2.0
3       Ana  Camaçari   Acessórios   Teclado   200.0         3.0
4     Bruno  Salvador  Eletrônicos  Notebook     0.0         1.0
5    Carlos  Camaçari   Acessórios     Mouse   150.0         0.0
6       Ana  salvador  Eletrônicos   Monitor  1150.0         2.0
7     Bruno  Camaçari  Eletrônicos  Notebook  3300.0         1.0
8    Carlos  Salvador   Acessórios   Teclado   220.0         3.0
9       Ana  Camaçari  Eletrônicos   Monitor  1250.0         1.0
10    Bruno  Salvador   Acessórios     Mouse   130.0         6.0
11   Carlos  Camaçari  Eletrônicos  Notebook  3450.0         2.0

In [19]:
df["total"] = df["preco"] * df["quantidade"]
df

   vendedor    cidade    categoria   produto   preco  quantidade   total
0       Ana  Salvador  Eletrônicos  Notebook  3500.0         2.0  7000.0
1     Bruno  Camaçari   Acessórios     Mouse   120.0         5.0   600.0
2    Carlos  salvador  Eletrônicos   Monitor  1200.0         2.0  2400.0
3       Ana  Camaçari   Acessórios   Teclado   200.0         3.0   600.0
4     Bruno  Salvador  Eletrônicos  Notebook     0.0         1.0     0.0
5    Carlos  Camaçari   Acessórios     Mouse   150.0         0.0     0.0
6       Ana  salvador  Eletrônicos   Monitor  1150.0         2.0  2300.0
7     Bruno  Camaçari  Eletrônicos  Notebook  3300.0         1.0  3300.0
8    Carlos  Salvador   Acessórios   Teclado   220.0         3.0   660.0
9       Ana  Camaçari  Eletrônicos   Monitor  1250.0         1.0  1250.0
10    Bruno  Salvador   Acessórios     Mouse   130.0         6.0   780.0
11   Carlos  Camaçari  Eletrônicos  Notebook  3450.0         2.0  6900.0

In [2]:
datavend = df.groupby("vendedor").agg(
    faturamento_total = ("total","sum"),
    quantidade_total = ("quantidade","sum")
).sort_values(0

SyntaxError: invalid syntax (2670442812.py, line 1)

In [1]:
df["cidade"] = df["cidade"].replace("salvador","Salvador")
df

NameError: name 'df' is not defined