In [1]:
import pandas as pd

players = pd.DataFrame({
    "player": [
        "Everton Ribeiro",
        "ERICK PULGA",
        "Jean Lucas",
        "Luciano Juba",
        "everton ribeiro",
        "Cauly",
        "ERICK PULGA",
        "Jean Lucas",
        "Cauly",
        "Luciano Juba"
    ],
    "position": [
        "Midfielder",
        "Forward",
        "Midfielder",
        "Left Back",
        "MIDFIELDER",
        "Midfielder",
        "FORWARD",
        "MIDFIELDER",
        "MIDFIELDER",
        "LEFT BACK"
    ],
    "competition": [
        "Brasileirao",
        "Copa do Brasil",
        "Brasileirao",
        "Brasileirao",
        "Brasileirao",
        "Copa do Brasil",
        "Brasileirao",
        "Copa do Brasil",
        "Brasileirao",
        "Copa do Brasil"
    ],
    "goals": [1, 3, 0, 1, 2, 1, 2, 1, 0, 0],
    "rating": [7.5, 8.7, 7.2, 7.8, 8.1, 7.6, 9.0, 7.9, 7.1, 7.4]
})

players

            player    position     competition  goals  rating
0  Everton Ribeiro  Midfielder     Brasileirao      1     7.5
1      ERICK PULGA     Forward  Copa do Brasil      3     8.7
2       Jean Lucas  Midfielder     Brasileirao      0     7.2
3     Luciano Juba   Left Back     Brasileirao      1     7.8
4  everton ribeiro  MIDFIELDER     Brasileirao      2     8.1
5            Cauly  Midfielder  Copa do Brasil      1     7.6
6      ERICK PULGA     FORWARD     Brasileirao      2     9.0
7       Jean Lucas  MIDFIELDER  Copa do Brasil      1     7.9
8            Cauly  MIDFIELDER     Brasileirao      0     7.1
9     Luciano Juba   LEFT BACK  Copa do Brasil      0     7.4

In [5]:
evertoncount = players["player"].str.contains("Everton",case=False)

evertoncounttop = players.loc[evertoncount]
evertoncounttop

            player    position  competition  goals  rating
0  Everton Ribeiro  Midfielder  Brasileirao      1     7.5
4  everton ribeiro  MIDFIELDER  Brasileirao      2     8.1

In [8]:
jean_appears = players["player"].str.contains("Jean",case=False)
result = jean_appears.sum()
print(f"{result} records has Jean in the player name")

2 records has Jean in the player name

In [9]:
players["player_clean"] = players["player"].str.lower()
players

            player    position     competition  goals  rating     player_clean
0  Everton Ribeiro  Midfielder     Brasileirao      1     7.5  everton ribeiro
1      ERICK PULGA     Forward  Copa do Brasil      3     8.7      erick pulga
2       Jean Lucas  Midfielder     Brasileirao      0     7.2       jean lucas
3     Luciano Juba   Left Back     Brasileirao      1     7.8     luciano juba
4  everton ribeiro  MIDFIELDER     Brasileirao      2     8.1  everton ribeiro
5            Cauly  Midfielder  Copa do Brasil      1     7.6            cauly
6      ERICK PULGA     FORWARD     Brasileirao      2     9.0      erick pulga
7       Jean Lucas  MIDFIELDER  Copa do Brasil      1     7.9       jean lucas
8            Cauly  MIDFIELDER     Brasileirao      0     7.1            cauly
9     Luciano Juba   LEFT BACK  Copa do Brasil      0     7.4     luciano juba

In [11]:
search_midfielder = players["position"].str.contains("Midfielder",case=False)
search_midfielderresult = players.loc[search_midfielder]
search_midfielderresult

            player    position     competition  goals  rating     player_clean
0  Everton Ribeiro  Midfielder     Brasileirao      1     7.5  everton ribeiro
2       Jean Lucas  Midfielder     Brasileirao      0     7.2       jean lucas
4  everton ribeiro  MIDFIELDER     Brasileirao      2     8.1  everton ribeiro
5            Cauly  Midfielder  Copa do Brasil      1     7.6            cauly
7       Jean Lucas  MIDFIELDER  Copa do Brasil      1     7.9       jean lucas
8            Cauly  MIDFIELDER     Brasileirao      0     7.1            cauly

In [23]:
rating = 8
counter = 0 
for index,line in players.iterrows():
    if line['competition'] == "Brasileirao" and line['rating'] >= rating:
        counter += 1

print(f"{counter} records of Brasileirão were rated with {rating} or more points!")

2 records of Brasileirão were rated with 8 or more points