In [6]:
import pandas as pd

data = {
    "player": [
        "Roger Gabriel", "Dell", "Ryan Nascimento",
        "Pedrinho", "Wendel", "Dyllan",
        "Caio Suassuna", "Saymon", "Emmanuel",
        "Fred Mundoco", "Kauê Furquim", "Roger Gabriel",
        "Dell", "Ryan Nascimento", "Pedrinho"
    ],
    "position": [
        "Midfielder", "Forward", "Forward",
        "Midfielder", "Defensive Midfielder", "Forward",
        "Forward", "Defensive Midfielder", "Midfielder",
        "Forward", "Forward", "Midfielder",
        "Forward", "Forward", "Midfielder"
    ],
    "age": [19, 17, 17, 20, 19, 18, 19, 18, 17, 18, 17, 19, 17, 17, 20],
    "training_attendance": [
        95, 88, 92, 90, 96, 85, 91, 94, 87, 89, 93, 97, 90, 86, 92
    ],
    "goals": [2, 4, 3, 1, 0, 5, 2, 0, 1, 3, 4, 1, 6, 2, 2],
    "rating": [8.2, 8.7, 8.4, 7.8, 7.6, 8.1, 8.0, 7.5, 7.3, 7.9, 8.5, 8.6, 9.1, 7.8, 8.0]
}

academydataframe = pd.DataFrame(data)
academydataframe

,player,position,age,training_attendance,goals,rating
0,Roger Gabriel,Midfielder,19,95,2,8.2
1,Dell,Forward,17,88,4,8.7
2,Ryan Nascimento,Forward,17,92,3,8.4
3,Pedrinho,Midfielder,20,90,1,7.8
4,Wendel,Defensive Midfielder,19,96,0,7.6
5,Dyllan,Forward,18,85,5,8.1
6,Caio Suassuna,Forward,19,91,2,8.0
7,Saymon,Defensive Midfielder,18,94,0,7.5
8,Emmanuel,Midfielder,17,87,1,7.3
9,Fred Mundoco,Forward,18,89,3,7.9
10,Kauê Furquim,Forward,17,93,4,8.5
11,Roger Gabriel,Midfielder,19,97,1,8.6
12,Dell,Forward,17,90,6,9.1
13,Ryan Nascimento,Forward,17,86,2,7.8
14,Pedrinho,Midfielder,20,92,2,8.0

In [7]:
totalrecords = len(academydataframe)
print(f"{totalrecords} records were registered!")

meanrating = academydataframe["rating"].mean()
print(f"{meanrating} points was the mean of the rating")


highestrating = academydataframe["rating"].idxmax()
highestratingdf = academydataframe.loc[highestrating]
print(f"The highest rating registered was {highestratingdf['rating']}\nData:\n")
highestratingdf

15 records were registered!
8.1 points was the mean of the rating
The highest rating registered was 9.1
Data:

player                    Dell
position               Forward
age                         17
training_attendance         90
goals                        6
rating                     9.1
Name: 12, dtype: object

In [11]:
counter = 0
print(f"Players with atleast 8.5 rating:\n")
for index,line in academydataframe.iterrows():
    if line["rating"] >= 8.5:
        counter += 1
        print(f"Player: {line['player']} ---- Position: {line['position']} ---- Rating: {line['rating']}")

print(f"{counter} records have atleast 8.5 rating")

Players with atleast 8.5 rating:

Player: Dell ---- Position: Forward ---- Rating: 8.7
Player: Kauê Furquim ---- Position: Forward ---- Rating: 8.5
Player: Roger Gabriel ---- Position: Midfielder ---- Rating: 8.6
Player: Dell ---- Position: Forward ---- Rating: 9.1
4 records have atleast 8.5 rating

In [17]:
counterattendance = 0
print(f"Players with attendance below 90% : \n")
for index,line in academydataframe.iterrows():
    if line["training_attendance"] < 90:
        counterattendance += 1
        print(f"Player: {line['player']} ---- Training Attendance {line['training_attendance']}\n")

print(f"{counterattendance} records have a training attendance below 90%")

Players with attendance below 90% :

Player: Dell ---- Training Attendance 88

Player: Dyllan ---- Training Attendance 85

Player: Emmanuel ---- Training Attendance 87

Player: Fred Mundoco ---- Training Attendance 89

Player: Ryan Nascimento ---- Training Attendance 86

5 records have a trainign attendance below 90%

In [20]:
academydataframe["development_status"] = academydataframe["rating"].apply(lambda x: "Excelent" if x >= 8.5 else ("Promising" if x >= 8.0 else "Needs Improvement")
)
academydataframe

,player,position,age,training_attendance,goals,rating,development_status
0,Roger Gabriel,Midfielder,19,95,2,8.2,Promising
1,Dell,Forward,17,88,4,8.7,Excelent
2,Ryan Nascimento,Forward,17,92,3,8.4,Promising
3,Pedrinho,Midfielder,20,90,1,7.8,Needs Improvement
4,Wendel,Defensive Midfielder,19,96,0,7.6,Needs Improvement
5,Dyllan,Forward,18,85,5,8.1,Promising
6,Caio Suassuna,Forward,19,91,2,8.0,Promising
7,Saymon,Defensive Midfielder,18,94,0,7.5,Needs Improvement
8,Emmanuel,Midfielder,17,87,1,7.3,Needs Improvement
9,Fred Mundoco,Forward,18,89,3,7.9,Needs Improvement
10,Kauê Furquim,Forward,17,93,4,8.5,Excelent
11,Roger Gabriel,Midfielder,19,97,1,8.6,Excelent
12,Dell,Forward,17,90,6,9.1,Excelent
13,Ryan Nascimento,Forward,17,86,2,7.8,Needs Improvement
14,Pedrinho,Midfielder,20,92,2,8.0,Promising

In [26]:
finalcounter = 0
for index,line in academydataframe.iterrows():
    if line["goals"] >= 3 and line["training_attendance"] >= 90:
        finalcounter += 1
        print(f"Player: {line['player']} ---- Scored Goals: {line['goals']} ---- Training Attendance: {line['training_attendance']} ---- Rating: {line['rating']}")

print(f"{finalcounter} records have atleast 3 scored goals and a Training attendance with atleast 90 percent!")

Player: Ryan Nascimento ---- Scored Goals: 3 ---- Training Attendance: 92 ---- Rating: 8.4
Player: Kauê Furquim ---- Scored Goals: 4 ---- Training Attendance: 93 ---- Rating: 8.5
Player: Dell ---- Scored Goals: 6 ---- Training Attendance: 90 ---- Rating: 9.1
3 records have atleast 3 scored goals and a Training attendance with atleast 90 percent!

In [31]:
academydataframe["goal_status"] = academydataframe["goals"].apply(lambda x: "Top Scorer" if x >= 4 else("Good Scoring" if x >= 2 and x <= 3 else "Needs more goals"))
academydataframe

,player,position,age,training_attendance,goals,rating,development_status,goal_status
0,Roger Gabriel,Midfielder,19,95,2,8.2,Promising,Good Scoring
1,Dell,Forward,17,88,4,8.7,Excelent,Top Scorer
2,Ryan Nascimento,Forward,17,92,3,8.4,Promising,Good Scoring
3,Pedrinho,Midfielder,20,90,1,7.8,Needs Improvement,Needs more goals
4,Wendel,Defensive Midfielder,19,96,0,7.6,Needs Improvement,Needs more goals
5,Dyllan,Forward,18,85,5,8.1,Promising,Top Scorer
6,Caio Suassuna,Forward,19,91,2,8.0,Promising,Good Scoring
7,Saymon,Defensive Midfielder,18,94,0,7.5,Needs Improvement,Needs more goals
8,Emmanuel,Midfielder,17,87,1,7.3,Needs Improvement,Needs more goals
9,Fred Mundoco,Forward,18,89,3,7.9,Needs Improvement,Good Scoring
10,Kauê Furquim,Forward,17,93,4,8.5,Excelent,Top Scorer
11,Roger Gabriel,Midfielder,19,97,1,8.6,Excelent,Needs more goals
12,Dell,Forward,17,90,6,9.1,Excelent,Top Scorer
13,Ryan Nascimento,Forward,17,86,2,7.8,Needs Improvement,Good Scoring
14,Pedrinho,Midfielder,20,92,2,8.0,Promising,Good Scoring

In [8]:
academydataframe["age_analyze"] = academydataframe["age"].apply(lambda x:"Promise" if x <= 18 else ("Regular" if x < 20 else "Too Old"))
academydataframe

,player,position,age,training_attendance,goals,rating,age_analyze
0,Roger Gabriel,Midfielder,19,95,2,8.2,Regular
1,Dell,Forward,17,88,4,8.7,Promise
2,Ryan Nascimento,Forward,17,92,3,8.4,Promise
3,Pedrinho,Midfielder,20,90,1,7.8,Too Old
4,Wendel,Defensive Midfielder,19,96,0,7.6,Regular
5,Dyllan,Forward,18,85,5,8.1,Promise
6,Caio Suassuna,Forward,19,91,2,8.0,Regular
7,Saymon,Defensive Midfielder,18,94,0,7.5,Promise
8,Emmanuel,Midfielder,17,87,1,7.3,Promise
9,Fred Mundoco,Forward,18,89,3,7.9,Promise
10,Kauê Furquim,Forward,17,93,4,8.5,Promise
11,Roger Gabriel,Midfielder,19,97,1,8.6,Regular
12,Dell,Forward,17,90,6,9.1,Promise
13,Ryan Nascimento,Forward,17,86,2,7.8,Promise
14,Pedrinho,Midfielder,20,92,2,8.0,Too Old