In [2]:
import pandas as pd

match_data = {
    "player": [
        "Lucas Ribeiro", "Mateus Santos", "Joao Pedro",
        "Gabriel Costa", "Rafael Lima", "Enzo Martins",
        "Pedro Henrique", "Caio Oliveira", "Bruno Alves",
        "Samuel Rocha", "Vitor Silva", "Davi Souza"
    ],
    "position": [
        "Forward", "Midfielder", "Defender", "Forward",
        "Midfielder", "Defender", "Goalkeeper", "Forward",
        "Defender", "Midfielder", "Forward", "Goalkeeper"
    ],
    "minutes_played": [90, 75, 90, 65, 80, 90, 90, 30, 85, 70, 60, 90],
    "successful_passes": [18, 54, 42, 12, 61, 48, 25, 7, 44, 58, 16, 32],
    "shots_on_target": [5, 2, 0, 7, 1, 1, 0, 4, 0, 2, 6, 0],
    "rating": [8.7, 7.9, 8.1, 9.0, 7.4, 8.3, 8.5, 7.8, 8.2, 7.6, 8.8, 8.0]
}

match_df = pd.DataFrame(match_data)
match_df

,player,position,minutes_played,successful_passes,shots_on_target,rating
0,Lucas Ribeiro,Forward,90,18,5,8.7
1,Mateus Santos,Midfielder,75,54,2,7.9
2,Joao Pedro,Defender,90,42,0,8.1
3,Gabriel Costa,Forward,65,12,7,9.0
4,Rafael Lima,Midfielder,80,61,1,7.4
5,Enzo Martins,Defender,90,48,1,8.3
6,Pedro Henrique,Goalkeeper,90,25,0,8.5
7,Caio Oliveira,Forward,30,7,4,7.8
8,Bruno Alves,Defender,85,44,0,8.2
9,Samuel Rocha,Midfielder,70,58,2,7.6
10,Vitor Silva,Forward,60,16,6,8.8
11,Davi Souza,Goalkeeper,90,32,0,8.0

In [26]:
top5playersrating = match_df.nlargest(5,"rating")
print(top5playersrating[['player','position','rating']])

            player    position  rating
3    Gabriel Costa     Forward     9.0
10     Vitor Silva     Forward     8.8
0    Lucas Ribeiro     Forward     8.7
6   Pedro Henrique  Goalkeeper     8.5
5     Enzo Martins    Defender     8.3

In [14]:
top3playerssucpas = match_df.nlargest(3,"successful_passes")
print(top3playerssucpas[['player','successful_passes']])

          player  successful_passes
4    Rafael Lima                 61
9   Samuel Rocha                 58
1  Mateus Santos                 54

In [21]:
filtered_df = match_df[(match_df["minutes_played"] >= 80)]
filtered_df

,player,position,minutes_played,successful_passes,shots_on_target,rating
0,Lucas Ribeiro,Forward,90,18,5,8.7
2,Joao Pedro,Defender,90,42,0,8.1
4,Rafael Lima,Midfielder,80,61,1,7.4
5,Enzo Martins,Defender,90,48,1,8.3
6,Pedro Henrique,Goalkeeper,90,25,0,8.5
8,Bruno Alves,Defender,85,44,0,8.2
11,Davi Souza,Goalkeeper,90,32,0,8.0

In [23]:
top1shots = filtered_df.nlargest(1,"shots_on_target")
print(top1shots[["player","position","shots_on_target"]])

          player position  shots_on_target
0  Lucas Ribeiro  Forward                5

In [34]:
filtered70_df = match_df[(match_df["minutes_played"] >= 70 & (match_df["successful_passes"] >= 40))]
filtered70_df

,player,position,minutes_played,successful_passes,shots_on_target,rating
0,Lucas Ribeiro,Forward,90,18,5,8.7
1,Mateus Santos,Midfielder,75,54,2,7.9
2,Joao Pedro,Defender,90,42,0,8.1
3,Gabriel Costa,Forward,65,12,7,9.0
4,Rafael Lima,Midfielder,80,61,1,7.4
5,Enzo Martins,Defender,90,48,1,8.3
6,Pedro Henrique,Goalkeeper,90,25,0,8.5
7,Caio Oliveira,Forward,30,7,4,7.8
8,Bruno Alves,Defender,85,44,0,8.2
9,Samuel Rocha,Midfielder,70,58,2,7.6
10,Vitor Silva,Forward,60,16,6,8.8
11,Davi Souza,Goalkeeper,90,32,0,8.0

In [39]:
totalrecords = len(filtered70_df)
print(filtered70_df[["player","minutes_played","rating"]])
print(f"\n{totalrecords} records have met both conditions!")

            player  minutes_played  rating
0    Lucas Ribeiro              90     8.7
1    Mateus Santos              75     7.9
2       Joao Pedro              90     8.1
3    Gabriel Costa              65     9.0
4      Rafael Lima              80     7.4
5     Enzo Martins              90     8.3
6   Pedro Henrique              90     8.5
7    Caio Oliveira              30     7.8
8      Bruno Alves              85     8.2
9     Samuel Rocha              70     7.6
10     Vitor Silva              60     8.8
11      Davi Souza              90     8.0

12 records have met both conditions!

In [43]:
lowestrating = filtered70_df["rating"].idxmin()
lowestplayer = filtered70_df.loc[lowestrating]
print(lowestplayer[["player","position","rating"]])

player      Rafael Lima
position     Midfielder
rating              7.4
Name: 4, dtype: object

In [53]:
filtered2shots = match_df[(match_df["shots_on_target"] >= 2)]
print(filtered2shots[["player","position","shots_on_target","rating"]])
averagerating = filtered2shots["rating"].mean()
print(f"\nThe average rating of these players is {averagerating}!")

           player    position  shots_on_target  rating
0   Lucas Ribeiro     Forward                5     8.7
1   Mateus Santos  Midfielder                2     7.9
3   Gabriel Costa     Forward                7     9.0
7   Caio Oliveira     Forward                4     7.8
9    Samuel Rocha  Midfielder                2     7.6
10    Vitor Silva     Forward                6     8.8

The average rating of these players is 8.299999999999999!

In [55]:
top2playersfilt = filtered2shots.nlargest(2,"shots_on_target")
print(top2playersfilt[["player","position","shots_on_target"]])

           player position  shots_on_target
3   Gabriel Costa  Forward                7
10    Vitor Silva  Forward                6